/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulerrajpokhreldzp5310;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Raj
 */
public class FlightSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form FlightSchedulerGUI
     */
    public FlightSchedulerGUI() {
        initComponents();
        fetchDataFromDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        addCustomer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        addCustomerDisplay = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookDateCombo = new javax.swing.JComboBox<>();
        bookFlightCombo = new javax.swing.JComboBox<>();
        seatAvailableTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookDisplayText = new javax.swing.JTextArea();
        bookButton = new javax.swing.JButton();
        bookUserName = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerNameCombox = new javax.swing.JComboBox<>();
        customerCheckBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        StatusTable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        statusDate = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        statusFlight = new javax.swing.JComboBox<>();
        statusSubmitButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        StatusTbale = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        waitlistCombo = new javax.swing.JComboBox<>();
        waitlistSubmitBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        waitListTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        flightName = new javax.swing.JTextField();
        seatnumber = new javax.swing.JLabel();
        numberofSeats = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        addFlightTextField = new javax.swing.JTextArea();
        addFlightBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addDateBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        addDateTextField = new javax.swing.JTextArea();
        datePicker = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dropFlightCombo = new javax.swing.JComboBox<>();
        dropBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        dropFlightDisplayText = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        canelUserName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cancelDateCombo = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        cancleDisplayText = new javax.swing.JTextArea();
        cancelBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane4.setBackground(new java.awt.Color(101, 171, 163));
        jTabbedPane4.setForeground(new java.awt.Color(25, 137, 253));
        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(101, 171, 163));

        addCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });
        addCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addCustomerKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Customer Name:");

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        addCustomerDisplay.setEditable(false);
        addCustomerDisplay.setColumns(20);
        addCustomerDisplay.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        addCustomerDisplay.setRows(5);
        jScrollPane9.setViewportView(addCustomerDisplay);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel13)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(addCustomer)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(54, 54, 54)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Add Customer ", jPanel3);

        jPanel2.setBackground(new java.awt.Color(101, 171, 163));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Name:");

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Flight:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Seat Available:");

        bookDateCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Date", " " }));
        bookDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDateComboActionPerformed(evt);
            }
        });

        bookFlightCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a Flight" }));
        bookFlightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightComboActionPerformed(evt);
            }
        });

        seatAvailableTextField.setEditable(false);
        seatAvailableTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bookDisplayText.setEditable(false);
        bookDisplayText.setColumns(20);
        bookDisplayText.setRows(5);
        jScrollPane1.setViewportView(bookDisplayText);

        bookButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        bookUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookUserName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bookUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date))
                                .addGap(130, 130, 130)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bookUserName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bookDateCombo, 0, 267, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookFlightCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatAvailableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 52, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bookUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(seatAvailableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane4.addTab("Book", jPanel2);

        jPanel1.setBackground(new java.awt.Color(101, 171, 163));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Name:");

        customerNameCombox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerNameCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick your Name" }));
        customerNameCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameComboxActionPerformed(evt);
            }
        });

        customerCheckBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerCheckBtn.setText("Check");
        customerCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCheckBtnActionPerformed(evt);
            }
        });

        customerTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Flight", "Date"
            }
        ));
        customerTable.setAlignmentX(1.0F);
        customerTable.setAlignmentY(1.0F);
        customerTable.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerCheckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerNameCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(customerCheckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane4.addTab("Customer", jPanel1);

        StatusTable.setBackground(new java.awt.Color(101, 171, 163));
        StatusTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Date:");

        statusDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        statusDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Date", " " }));
        statusDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Flight:");

        statusFlight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        statusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Flight" }));
        statusFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFlightActionPerformed(evt);
            }
        });

        statusSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        statusSubmitButton.setText("Submit");
        statusSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusSubmitButtonActionPerformed(evt);
            }
        });

        StatusTbale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StatusTbale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer", "Date", "Flight"
            }
        ));
        jScrollPane4.setViewportView(StatusTbale);

        javax.swing.GroupLayout StatusTableLayout = new javax.swing.GroupLayout(StatusTable);
        StatusTable.setLayout(StatusTableLayout);
        StatusTableLayout.setHorizontalGroup(
            StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusTableLayout.createSequentialGroup()
                .addGroup(StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusTableLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(128, 128, 128)
                        .addGroup(StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusFlight, 0, 317, Short.MAX_VALUE)
                            .addComponent(statusSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(StatusTableLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        StatusTableLayout.setVerticalGroup(
            StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusTableLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(StatusTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(statusSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane4.addTab("Status", StatusTable);

        jPanel4.setBackground(new java.awt.Color(101, 171, 163));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Date:");

        waitlistCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        waitlistCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Date" }));

        waitlistSubmitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        waitlistSubmitBtn.setText("Submit");
        waitlistSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistSubmitBtnActionPerformed(evt);
            }
        });

        waitListTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waitListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Date", "Flight", "Time"
            }
        ));
        jScrollPane3.setViewportView(waitListTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waitlistSubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waitlistCombo, 0, 285, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(waitlistCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(waitlistSubmitBtn)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Wait list", jPanel4);

        jPanel5.setBackground(new java.awt.Color(101, 171, 163));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Flight Name:");

        flightName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        seatnumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seatnumber.setText("Number of Seats:");

        numberofSeats.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        addFlightTextField.setColumns(20);
        addFlightTextField.setRows(5);
        jScrollPane5.setViewportView(addFlightTextField);

        addFlightBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addFlightBtn.setText("Add");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(seatnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberofSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(380, 380, 380))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(flightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatnumber)
                    .addComponent(numberofSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(addFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Add Flight", jPanel5);

        jPanel6.setBackground(new java.awt.Color(101, 171, 163));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Date:");

        addDateBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addDateBtn.setText("Add");
        addDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateBtnActionPerformed(evt);
            }
        });

        addDateTextField.setEditable(false);
        addDateTextField.setColumns(20);
        addDateTextField.setRows(5);
        jScrollPane6.setViewportView(addDateTextField);

        datePicker.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel9)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(addDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Add Day", jPanel6);

        jPanel7.setBackground(new java.awt.Color(101, 171, 163));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Flight:");

        dropFlightCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Flight" }));

        dropBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dropBtn.setText("Drop");
        dropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBtnActionPerformed(evt);
            }
        });

        dropFlightDisplayText.setEditable(false);
        dropFlightDisplayText.setColumns(20);
        dropFlightDisplayText.setRows(5);
        jScrollPane7.setViewportView(dropFlightDisplayText);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel10)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dropBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(dropFlightCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(dropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Drop Flight", jPanel7);

        jPanel8.setBackground(new java.awt.Color(101, 171, 163));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Name:");

        canelUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Date:");

        cancelDateCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Date" }));

        cancleDisplayText.setEditable(false);
        cancleDisplayText.setColumns(20);
        cancleDisplayText.setRows(5);
        jScrollPane8.setViewportView(cancleDisplayText);

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(92, 92, 92)
                                .addComponent(canelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(112, 112, 112)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelDateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(canelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(53, 53, 53)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Canel", jPanel8);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(28, 48, 154));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(122, 246, 238));
        jTextField1.setText("   Welcome to the Flight Scheduler");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void customerCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCheckBtnActionPerformed
        // TODO add your handling code here:
        
        ArrayList<BookingEntry> list = Booking.getCustomerByName(customerNameCombox.getSelectedItem().toString());
        DefaultTableModel model = (DefaultTableModel)customerTable.getModel();
        model.setNumRows(0);
        for (BookingEntry entry : list) 
        {
            String[] bookings = new String[3];
            bookings[0] = entry.getCustomer();
            bookings[1] = entry.getDay();
            bookings[2] = entry.getFlight();
            model.addRow(bookings);
        } 
    }//GEN-LAST:event_customerCheckBtnActionPerformed

    private void statusSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusSubmitButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)StatusTbale.getModel();
        ArrayList<Customer> list = Booking.getBookingsByFlightAndDay(statusDate.getSelectedItem().toString(), statusFlight.getSelectedItem().toString());
        model.setNumRows(0);
       
        for (Customer entry : list) 
        {
            String[] bookings = new String[3];
            bookings[0] = entry.getName();
            bookings[1] = statusDate.getSelectedItem().toString();
            bookings[2] = statusFlight.getSelectedItem().toString();
            model.addRow(bookings);
        }
    }//GEN-LAST:event_statusSubmitButtonActionPerformed

    private void waitlistSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistSubmitBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) waitListTable.getModel();
        ArrayList<WaitlistEntry> list = Waitlist.getWaitlistStatus(waitlistCombo.getSelectedItem().toString());
        model.setNumRows(0);

        for (WaitlistEntry entry : list) 
        {
            String[] bookings = new String[4];
            bookings[0] = entry.getCustomer();
            bookings[1] = entry.getDate();
            bookings[2] = entry.getFlight();
            bookings[3] = entry.getTimestamp().toString();
            model.addRow(bookings);
        }  

    }//GEN-LAST:event_waitlistSubmitBtnActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
        addFlightTextField.setText(null);
        Flight.addFlightsandSeats(new FlightEntry(flightName.getText(), Integer.parseInt(numberofSeats.getText())));
        addFlightTextField.append("Flight "+flightName.getText().toString()+" is added with "+ numberofSeats.getText().toString()+" seats");
        
         bookFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         statusFlight.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         dropFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void addDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateBtnActionPerformed
        // TODO add your handling code here:
       addDateTextField.setText(null);
       Date oDate = datePicker.getDate();        
       DateFormat oDateFormat = new SimpleDateFormat("MM-dd-yyyy");
       String szDate = oDateFormat.format(oDate);
       Day.addDate(szDate);
       addDateTextField.append(szDate);
       
       //update dates for each combo box
        bookDateCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
        statusDate.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
        waitlistCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
        cancelDateCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray())); 

    }//GEN-LAST:event_addDateBtnActionPerformed

    private void dropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBtnActionPerformed
        // TODO add your handling code here:
        String flight = dropFlightCombo.getSelectedItem().toString();
        ArrayList<String> Bookdrop = Flight.dropFlight(flight);
        ArrayList<String> Waitlistdrop =  Waitlist.dropFlight(flight);
        dropFlightDisplayText.setText(null);
        for(int i=0;i<Bookdrop.size();i++)
           dropFlightDisplayText.append(Bookdrop.get(i));
        dropFlightDisplayText.append("\n");
        for(int i=0;i<Waitlistdrop.size();i++)
            dropFlightDisplayText.append(Waitlistdrop.get(i));
        
         bookFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         statusFlight.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         dropFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));    
         waitlistCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
    }//GEN-LAST:event_dropBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:  
       cancleDisplayText.setText(null);
       cancleDisplayText.append(Booking.deleteBooking(canelUserName.getText(),cancelDateCombo.getSelectedItem().toString()));      
       customerNameCombox.setModel(new DefaultComboBoxModel(Booking.getCustomers().toArray()));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void customerNameComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameComboxActionPerformed
        // TODO add your handling code here:         
    }//GEN-LAST:event_customerNameComboxActionPerformed

    private void statusDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDateActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_statusDateActionPerformed

    private void statusFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFlightActionPerformed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_addCustomerActionPerformed

    private void addCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addCustomerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerKeyPressed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
       
        if(!addCustomer.getText().equals(""))
        {
             Customer.addCustomer(addCustomer.getText()); 
            addCustomerDisplay.setText(addCustomer.getText()+" has been added!!!");      
            bookUserName.setModel(new DefaultComboBoxModel(Customer.getCustomers().toArray()));
        }
        else 
            addCustomerDisplay.setText("Please enter a custoner name");       
       
    }//GEN-LAST:event_addBtnActionPerformed

    private void bookUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookUserNameActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        bookDisplayText.setText(null);
        int seats = 0;
        seats = Flight.getFlightSeats(bookFlightCombo.getSelectedItem().toString());
        if ((!bookUserName.getSelectedItem().toString().equals("") && !bookDateCombo.getSelectedItem().toString().equals(null) && !bookFlightCombo.getSelectedItem().toString().equals(null)))
        {
            Booking.addBooking(new BookingEntry(bookUserName.getSelectedItem().toString(),bookDateCombo.getSelectedItem().toString(),bookFlightCombo.getSelectedItem().toString()));
            if(seats != 0)
            bookDisplayText.append("Customer "+ bookUserName.getSelectedItem().toString() + " has been booked on flight "+ bookFlightCombo.getSelectedItem().toString()+ " on " +bookDateCombo.getSelectedItem().toString());
            else
            bookDisplayText.append("Customer "+ bookUserName.getSelectedItem().toString() + " has been wailtlisted on flight "+ bookFlightCombo.getSelectedItem().toString()+ " on " +bookDateCombo.getSelectedItem().toString());
            customerNameCombox.setModel(new DefaultComboBoxModel(Booking.getCustomers().toArray()));
        }
        else
        {
            bookDisplayText.append("Booking failed \n");
            bookDisplayText.append("Please enter all the informations above!!");
        }
        seatAvailableTextField.setText((String.valueOf(Flight.getFlightSeats(bookFlightCombo.getSelectedItem().toString()))));
    }//GEN-LAST:event_bookButtonActionPerformed

    private void bookFlightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightComboActionPerformed
        // TODO add your handling code here:
        seatAvailableTextField.setText((String.valueOf(Flight.getFlightSeats(bookFlightCombo.getSelectedItem().toString()))));
    }//GEN-LAST:event_bookFlightComboActionPerformed

    private void bookDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookDateComboActionPerformed
    
    //Fetch data from the Database when the application is open
    public void fetchDataFromDB()
    {
         bookUserName.setModel(new DefaultComboBoxModel(Customer.getCustomers().toArray()));
         bookDateCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
         bookFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         statusDate.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
         statusFlight.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         waitlistCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray()));
         customerNameCombox.setModel(new DefaultComboBoxModel(Booking.getCustomers().toArray()));
         dropFlightCombo.setModel(new DefaultComboBoxModel(Flight.getFlights().toArray()));
         cancelDateCombo.setModel(new DefaultComboBoxModel(Day.getdates().toArray())); 
         
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusTable;
    private javax.swing.JTable StatusTbale;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addCustomer;
    private javax.swing.JTextArea addCustomerDisplay;
    private javax.swing.JButton addDateBtn;
    private javax.swing.JTextArea addDateTextField;
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextArea addFlightTextField;
    private javax.swing.JButton bookButton;
    private javax.swing.JComboBox<String> bookDateCombo;
    private javax.swing.JTextArea bookDisplayText;
    private javax.swing.JComboBox<String> bookFlightCombo;
    private javax.swing.JComboBox<String> bookUserName;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cancelDateCombo;
    private javax.swing.JTextArea cancleDisplayText;
    private javax.swing.JTextField canelUserName;
    private javax.swing.JButton customerCheckBtn;
    private javax.swing.JComboBox<String> customerNameCombox;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JButton dropBtn;
    private javax.swing.JComboBox<String> dropFlightCombo;
    private javax.swing.JTextArea dropFlightDisplayText;
    private javax.swing.JTextField flightName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField numberofSeats;
    private javax.swing.JTextField seatAvailableTextField;
    private javax.swing.JLabel seatnumber;
    private javax.swing.JComboBox<String> statusDate;
    private javax.swing.JComboBox<String> statusFlight;
    private javax.swing.JButton statusSubmitButton;
    private javax.swing.JTable waitListTable;
    private javax.swing.JComboBox<String> waitlistCombo;
    private javax.swing.JButton waitlistSubmitBtn;
    // End of variables declaration//GEN-END:variables
}
